### ISSUE TITLE
New Channel Request: #ut-lehi-downtown

### ISSUE THREAD

**Issue by quinnj** [ZRiddle/PokeAlertsOnboarding#1]
Channel Name: #ut-lehi-downtown
Map Link: http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.412105, -111.906867%0A40.386548, -111.829019

This should border the #ut-lehi-1200w3200n channel directly to the south and is non-overlapping.

This will cover the Lehi downtown area (main st. around the library area, 15+ pokestops and 5-10 gyms). Also goes out west around Willow Park (10-15 pokestops, 3 gyms), and includes the Lehi cemetery (15-20 pokestops, several gyms).

Love the project!

**Comment by TheBoberton** [comment]
Came here to request this exact area. 

I think there are a couple of spaces in the link however. Try: 
http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.412105,-111.906867%0A40.386548,-111.829019

Thanks everybody. If there is more I can do to help make this channel happen hit me up in slack @theboberton.

**Comment by plampy** [comment]
Created!
