### ISSUE TITLE
New Channel Request: West Valley

### ISSUE THREAD

**Issue by jcalloway** [ZRiddle/PokeAlertsOnboarding#15]
Channel Name = #ut-westvalley-valleyfairmall

Map Link = http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.704054,-111.981527%0A40.704054,-111.952772%0A40.667656,-111.952695%0A40.667656,-111.981527

**Comment by anglesey26** [comment]
I would like that as well

**Comment by ZRiddle** [comment]
Crawling a larger zone to mirror #18 Kearns

1701 Spawnpoints so far

```
{
  "CrawlerZones": [
    {
      "Name": "ut-west-valley",
      "Bounds": {
        "MaxLat": 40.704054,
        "MinLon": -112.044033,
        "MinLat": 40.667656,
        "MaxLon": -111.952772
    }
```

**Comment by plampy** [comment]
Added, #ut-west-valley
