### ISSUE TITLE
#ut- Pleasant grove

### ISSUE THREAD

**Issue by ParkerRobertson** [ZRiddle/PokeAlertsOnboarding#16]
Just wanted to formally request a channel. I know you have other more popular channel request & work your ass off so I understand if this has to wait a while or cant happen. I also know creating a new channel might be more difficult with the new crawlers. Anyway here is the map link:

[http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.383195,-111.759549%0A40.344040,-111.698041]

http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.383195,-111.759549%0A40.344040,-111.698041

**Comment by ZRiddle** [comment]
I have some bots mapping out spawnpoints in this area now

**Comment by ZRiddle** [comment]
Refer to issue #22 for Pleasant Grove
https://github.com/ZRiddle/PokeAlertsOnboarding/issues/22
