### ISSUE TITLE
#ut-kearns-olympic oval

### ISSUE THREAD

**Issue by keaster** [ZRiddle/PokeAlertsOnboarding#18]
http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.667622,-111.952976%0A40.667741,-112.046227%0A40.623556,-112.044033%0A40.623967,-111.951339

**Comment by ZRiddle** [comment]
started some bots to map out spawns here

**Comment by ZRiddle** [comment]
1583 Spawnpoints so far

```
{
  "CrawlerZones": [
    {
      "Name": "ut-kearns",
      "Bounds": {
        "MaxLat": 40.667622,
        "MinLon": -112.044033,
        "MinLat": 40.623556,
        "MaxLon": -111.952976
    }
```

**Comment by plampy** [comment]
#ut-kearns created
