### ISSUE TITLE
New Channel Please!!!!!   #ut-slc-glendale

### ISSUE THREAD

**Issue by polishninja242** [ZRiddle/PokeAlertsOnboarding#2]
Channel Name: #ut-slc-glendale
Map Link: http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.704054,-111.972772%0A40.741695,-111.972772%0A40.741695,-111.902619%0A40.704054,-111.902619%0A40.704054,-111.972772

This should border the #ut-taylorsville
This will cover the Glendale area, which includes Seven Peaks water park and The International Peace Gardens (which has 15 stops in a small area and lots of Charmanders!)
Thanks for all the hard wor!

**Comment by plampy** [comment]
#ut-slc-glendale created. Its a little big, and if its slow ill split it in half behind the scenes.

**Comment by polishninja242** [comment]
Thank you!!!!
