### ISSUE TITLE
#ut-pleasantgrove-lindon

### ISSUE THREAD

**Issue by NaterRampager** [ZRiddle/PokeAlertsOnboarding#22]
This request will fill the gap between Orem and American Fork. There's another req for Pleasant Grove, but mine seems to be a bit more inclusive up to the Cedar Hills bottom border.
# ut-pleasantgrove-lindon

http://www.s2map.com/#order=latlng&mode=polygon&s2=false&points=40.392,-111.769%0A40.3335,-111.67

**Comment by ZRiddle** [comment]
2383 Spawnpoints so far

```
{
  "CrawlerZones": [
    {
      "Name": "ut-pleasantgrove",
      "Bounds": {
        "MaxLat": 40.392,
        "MinLon": -111.769,
        "MinLat": 40.3335,
        "MaxLon": -111.67
      }
```

**Comment by cujo85** [comment]
Any idea when this one will be up and running?

**Comment by ZRiddle** [comment]
We're fixing up the orem ones before we roll this out so the maps aren't whack

**Comment by ZRiddle** [comment]
refer to #23 for this
