### ISSUE TITLE
Expanding Orem

### ISSUE THREAD

**Issue by cdabs** [ZRiddle/PokeAlertsOnboarding#23]
Hey I was wondering if we could expand the Orem Timp location a little bit. It stops at 8th north and there currently are no maps covering 8th-center in Orem. I have map out the coordiantes 40.333623, -111.72924   40.296952, -111.666289. What do you think?

**Comment by seastland** [comment]
It might be better to create a new #ut-orem-central channel so that Riverwoods can be included too.  The Timp boundaries don't go far enough East.

These boundaries are directly above #ut-orem-provo:

http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.311636,%0A-111.7550486%0A40.298123574,%0A-111.6288480%0A

**Comment by cdabs** [comment]
I like that idea too!

**Comment by AndraesBoni** [comment]
I think it should look like this
![orem](https://cloud.githubusercontent.com/assets/21106871/17782536/315f0ac8-6531-11e6-8bb4-9ebd8cbe3954.PNG)
I've contacted the guy in charge about doing some mapping for him.  Hopefully we'll get it cleaned up nicely.

**Comment by seastland** [comment]
I like those boundaries.

**Comment by cdabs** [comment]
I really like this idea, a lot cleaner!

**Comment by plampy** [comment]
Can you post the latitude and longitude bounds you're using for the zones in that image? This seems like a great way to split that area up.

**Comment by AndraesBoni** [comment]
I did adjust it a bit from the image above, making BYU a little smaller, here are the NW and SE corners for each area. 
(tab separated)
FID Shape \* Id  W   N   name
12  Point   0   -111.759    40.3336 vineyard
13  Point   0   -111.729    40.2732 vineyard
14  Point   0   -111.729    40.3116 orem-central
15  Point   0   -111.633    40.2732 orem-central
16  Point   0   -111.741    40.2732 provo-west
17  Point   0   -111.684    40.2123 provo-west
18  Point   0   -111.684    40.2732 provo-byu
19  Point   0   -111.625    40.2258 provo-byu
20  Point   0   -111.684    40.2258 provo-south
21  Point   0   -111.606    40.1858 provo-south

**Comment by AndraesBoni** [comment]
oops I forgot to include the extended timp boundary:

FID Shape \* Id  W   N   name
0   Point   0   -111.665    40.3116 orem-timp
1   Point   0   -111.729    40.3336 orem-timp

Is this a good format for these?  would all 4 corners be better? I can easily do any kind of useful output.  I have the whole rest of utah and SL valleys all squared off.  Should I just post those here?

**Comment by plampy** [comment]
Yeah! that would be awesome. Most of the areas we have right now are allllll over the place in size and don't always line up. It would be great to get everything aligned better. We're configuring things on our side with max lat, min lon, min lat, and max lon if you'd be up for switching the formatting (ex: ut-south-mountain: 40.501000, -111.89100, 40.48341, -111.83893)

**Comment by plampy** [comment]
This is in effect now!
