### ISSUE TITLE
 #ut-lehi-traverse - The very top neighborhood got left out

### ISSUE THREAD

**Issue by roboticsplits** [ZRiddle/PokeAlertsOnboarding#24]
Current Channel: #ut-lehi-traverse 

Proposed Updated Map:
http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.457303,%0A-111.915866%0A40.432689,%0A-111.849591%0A%0A%0A

Not important but the attached pic shows the neighborhood that got left out:
![chestnut greyhawk neighborhood](https://cloud.githubusercontent.com/assets/21091267/17756046/c1424354-649a-11e6-8936-5268106a9c3a.jpg)

It's very small, but I live up there and it has some great finds...in the past couple days I've caught a Snorlax, Weepingbell, Chancey, Charmander, Gastley, etc. It would mean a lot to me : )

Also, you're freakin awesome! Thanks for all you do!

**Comment by ZRiddle** [comment]
moving zone to cover it

**Comment by roboticsplits** [comment]
Thanks for doing that. I know y'all are so busy but I haven't seen any listings in this area...I will comment again when I see it.

Thanks for all you do, you guys are rockstars.
