### ISSUE TITLE
New spots in Idaho

### ISSUE THREAD

**Issue by awesomeaustinandersen** [ZRiddle/PokeAlertsOnboarding#25]
I started using the app in Utah with my extended family but now I cant use it in Idaho. It would be awesome if we could have **#id Meridian** and if possible, **#id Boise**. If coordinates are needed, Meridian is at 43.612343, -116.393707 and for Boise: 43.618881, -116.215019. Thanks!!!

**Comment by ZRiddle** [comment]
We aren't going outside of Utah at this point
