### ISSUE TITLE
#ut-midvale-angelstreet

### ISSUE THREAD

**Issue by egarff** [ZRiddle/PokeAlertsOnboarding#27]
# ut-midvale-angelstreet

Lat: 40.620000,-111.86300
Lng: 40.595500,-111.89100

**Comment by egarff** [comment]
http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.620000,-111.86300%0A40.595500,-111.89100

**Comment by ZRiddle** [comment]
We need the midvale one to line up with the west jordan one and the murray one that we just made
