### ISSUE TITLE
Daybreak area

### ISSUE THREAD

**Issue by pokeninja** [ZRiddle/PokeAlertsOnboarding#28]
# ut-southjordan-daybreak

40.544197,-111.957756
40.562004,112.010309

I tried my best to make it about the size of the example as well as border the #ut-riverton-district map. If there is any other information you would like me to provide just let me know.

**Comment by ZRiddle** [comment]
We're collecting spawnpoint for this now.

We're also redoing the zones over there so it may look different

**Comment by markomrtnz** [comment]
So any word on when it's coming out

**Comment by plampy** [comment]
Created #ut-daybreak, updated map
