### ISSUE TITLE
New area redwood and 10400

### ISSUE THREAD

**Issue by rhino717** [ZRiddle/PokeAlertsOnboarding#3]

**Comment by plampy** [comment]
If you can map out the area you want, that would be great! Instructions are on https://github.com/ZRiddle/PokeAlertsOnboarding#can-you-put-bots-in-my-area

**Comment by ZRiddle** [comment]
Closing this.  Make a new one with coords.  Use this link https://github.com/ZRiddle/PokeAlertsOnboarding#can-you-put-bots-in-my-area
