### ISSUE TITLE
Ut-Bluffdale-Bangerter

### ISSUE THREAD

**Issue by bdizzle08** [ZRiddle/PokeAlertsOnboarding#31]
In the neighborhood's in this area we've seen rare Pokemon and this is a gap between the riverton district and draper bangerter and Herriman areas. 

Square from 40.514116, -111.987333 to 40.476054, -111.922445

This stretches up to the riverton hospital and includes the south side of bangerter neighborhood's in bluffdale. 

Thanks

**Comment by ZRiddle** [comment]
Changing up borders so that it borders
#ut-draper-bangerter
#ut--herriman
#ut-south-jordan

```
{
  "CrawlerZones": [
    {
      "Name": "ut-bluffdale",
      "Bounds": {
        "MaxLat": 40.5224130, 
        "MinLon": -111.995847,
        "MinLat": 40.476054,
        "MaxLon": -111.928968
      }
```

**Comment by ZRiddle** [comment]
This has spawnpoints mapped now

**Comment by plampy** [comment]
up and running in #ut-bluffdale
