### ISSUE TITLE
#ut-slc-cemetary

### ISSUE THREAD

**Issue by ModestZombie** [ZRiddle/PokeAlertsOnboarding#33]
40.775764,-111.870003
40.792000,-111.825000

I would recommend seeing if there was a way to combine #ut-slc-capitol & #ut-slc-cemetary, seeing as they are only extending the reach of #ut-slc-gateway & #ut-slc-uofu. Or maybe extend the originals? I've seen to many legendary spawns at the capitol and greater Ave's, I'd love to have this place covered.

**Comment by plampy** [comment]
Consolidating this with #34
