### ISSUE TITLE
Request: 9000 s State St

### ISSUE THREAD

**Issue by spooner01** [ZRiddle/PokeAlertsOnboarding#4]
I'm not sure what details you need, but the area is not represented in the listings already. I would love to help if I can.

**Comment by plampy** [comment]
If you can map out the area you want, that would be great!  Instructions are on https://github.com/ZRiddle/PokeAlertsOnboarding#can-you-put-bots-in-my-area

**Comment by ZRiddle** [comment]
Resubmit with map
