### ISSUE TITLE
#ut-midvale-union

### ISSUE THREAD

**Issue by HonorKnight** [ZRiddle/PokeAlertsOnboarding#42]
Channel name = #ut-midvale-union

Map link = http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.6302,-111.9027,40.5948,-111.8548

"Super Bonus Internet Points": this should be pretty much flush against #ut-murray, #ut-westjordan-east, and #ut-sandy-megaplex. It slightly overlaps #ut-sandy-ftunion, but moving it further west would remove some key locations. The sandy locations should probably be shifted around anyway to not overlap each other.

**Comment by ZRiddle** [comment]
We already have plans to roll out this area https://www.scribblemaps.com/maps/view/pogo/erduFdF20m2
