### ISSUE TITLE
#ut-southjordan-daybreak

### ISSUE THREAD

**Issue by markomrtnz** [ZRiddle/PokeAlertsOnboarding#44]
http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.587917,-112.024149%0A40.522232,-111.984143

**Comment by markomrtnz** [comment]
I pooched this one rumor has it there's one coming?

**Comment by zazomazo** [comment]
http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.567917,-112.024149%0A40.522232,-111.984143

This is my recommendation. Keep it closer knit to find localized pokemon. Please make this area available. The lake has a lot of spawns.

**Comment by markomrtnz** [comment]
Seems like a good idea

**Comment by plampy** [comment]
This has a lot of overlap with #28 so I'm closing this and widening the other request.
