### ISSUE TITLE
Share raw data?

### ISSUE THREAD

**Issue by HonorKnight** [ZRiddle/PokeAlertsOnboarding#47]
Given that this project seems to do more than just send alerts, but rather has some history of what has spawned (how else could it identify nests in NestLocations.md?), is there perchance a persistent database of spawns? Any chance of making this available for querying or copying? I'd love to be able to dig around and see if more information beyond just nest locations can be derived from it.

**Comment by plampy** [comment]
Yes, we are logging these spawns. We don't currently have plans to open source that data beyond the nest locations that we've disclosed.
