### ISSUE TITLE
West Jordan Area Request

### ISSUE THREAD

**Issue by BatBoss** [ZRiddle/PokeAlertsOnboarding#5]
I sent some coordinates for West Jordan before all the bots died, but here's one that borders an existing territory (taylorsville):
Possible names:
ut-wjordan-vtrns-mmrl
(Veteran's memorial park)

Or -

ut-westjordan-east

http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.641695,-111.95277240.641695,-111.90261940.587885,%20-111.90261940.587885,%20-111.952772

**Comment by BatBoss** [comment]
The link doesn't seem to work for some reason. Here are the coordinates:
40.641695,-111.952772
40.641695,-111.902619
40.587885, -111.902619
40.587885, -111.952772

**Comment by ZRiddle** [comment]
Fixed link for reference
http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.641695,-111.952772%0A40.587885,-111.902619
