### ISSUE TITLE
ut-southjordan-central

### ISSUE THREAD

**Issue by tryer1** [ZRiddle/PokeAlertsOnboarding#57]
+40.55873, -111.98298
  +40.58743, -111.90269

This is the area left open on the map filling in the South Jordan to day break to west jordan zones - Hope this helps having the coordinates as above - thanks for your service!!

**Comment by tryer1** [comment]
Here is the link to your map program

http://s2map.com/#order=latlng&mode=polygon&s2=false&points=+40.55873, -111.98298%0A+40.58743, -111.90269

**Comment by plampy** [comment]
Created #ut-southjordan-centrl
