### ISSUE TITLE
Alpine/Highland/Cedar Hills zones

### ISSUE THREAD

**Issue by mattacm** [ZRiddle/PokeAlertsOnboarding#7]
Cedar Hills
# ut-cedarhills

http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.391787,-111.736815%0A40.432278,-111.732244%0A40.431717,-111.773379%0A40.392081,-111.782906

Alpine
# ut-alpine

http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.432052961738336,-111.82099342346191%0A40.479728573402575,-111.74786567687988%0A

Highland
# ut-highland

http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.40558820460205,-111.830735206604%0A40.43218362606488,-111.77314281463623
OR
# ut-highland-NElehi

http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.405635,-111.850133%0A40.43218362606488,-111.77314281463623
This link picks up the chunk of lehi leftover between the highland city border and the #ut-lehi-1200w3200n channel zone line (Or we extend the 1200w3200n zone east another block to the highland city line)

American Fork
# ut-af-north

http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.405588,-111.830735%0A40.405439,-111.789021%0A40.392081,-111.782906%0A40.391558,-111.759131%0A40.383158,-111.759346%0A40.382868,-111.830435%0A%0A
Not sure if you can do that many coordinates to make a zone but this is the chunk of AF missing if we map out the existing zones being requested. This would border on four other zones.

**Comment by plampy** [comment]
New zones are up and running
