### ISSUE TITLE
Twitter hashtags

### ISSUE THREAD

**Issue by HonorKnight** [ZRiddle/PokeAlertsOnboarding#75]
Please use some sort of hashtags in your twitter messages. I.e. instead of "Dragonite spotted in Sandy", maybe "#PokeAlertSandy #SandyDragonite" or something to that effect. That way people can filter to their area or the specific pokemon they want to catch in their area instead of being spammed with spawns all across the valley.

**Comment by ZRiddle** [comment]
This isn't twitter

**Comment by HonorKnight** [comment]
So where would this request belong? This is the only repository you've provided a link to.
