### ISSUE TITLE
New Channel Request: #ut-af-500east

### ISSUE THREAD

**Issue by quinnj** [ZRiddle/PokeAlertsOnboarding#8]
Map Link: http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.382868,-111.814384%0A40.333030,-111.759453

**Comment by plampy** [comment]
I moved the upper latitude bound up slightly to run along side the lehi zone. Bounds are http://s2map.com/#order=latlng&mode=polygon&s2=false&points=40.386548,-111.814384%0A40.333030,-111.759453%0A%0A

I'll update the docs tomorrow with the channel + zone link
